In [2]:
import numpy as np

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix.shape  # dimension
matrix.dtype  # data type
matrix.device  # cpu
print(matrix.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [3]:
matrix.flatten("A")
matrix.flatten("C")

array([1, 2, 3, 4, 5, 6])

💡 This is literally linear regression


In [9]:
X = np.array([[1500, 3], [1800, 4], [1200, 2]])  # house size, rooms
weights = np.array([0.5, 1.2])
prediction = X @ weights  # Multiply matrix X with vector weights
print(prediction)

[753.6 904.8 602.4]


In [4]:
np.std(X)

np.float64(768.2789749390083)

In [5]:
np.mean(X)

np.float64(751.5)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # vector addition✅[1+4, 2+5, 3+6]
print(a * b)  # element-wise multiplication ✅[1*4, 2*5, 3*6]
print(a @ b) #@ = dot / matrix multiplication ✅ 1*4 + 2*5 + 3*6 = 32

[5 7 9]
[ 4 10 18]
32
